import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, Alert, Share } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { NavigationBar } from '@/components/NavigationBar';
import { useTheme } from '@/contexts/ThemeContext';
import { useUser } from '@/contexts/UserContext';
import { useDashboardStatus } from '@/hooks/useDashboardStatus';

interface ExportOptionProps {
  iconName: keyof typeof Ionicons.glyphMap;
  title: string;
  description: string;
  onPress: () => void;
  darkMode?: boolean;
  color: string;
  bgColor: string;
}

function ExportOption({ iconName, title, description, onPress, darkMode, color, bgColor }: ExportOptionProps) {
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [
        styles.exportOption,
        darkMode && styles.exportOptionDark,
        pressed && styles.exportOptionPressed,
      ]}
    >
      <View style={[styles.iconContainer, { backgroundColor: bgColor }]}>
        <Ionicons name={iconName} size={24} color={color} />
      </View>
      <View style={styles.textContainer}>
        <Text style={[styles.title, darkMode && styles.titleDark]}>{title}</Text>
        <Text style={[styles.description, darkMode && styles.descriptionDark]}>{description}</Text>
      </View>
      <View style={styles.arrowContainer}>
        <Ionicons 
          name="chevron-forward" 
          size={20} 
          color={darkMode ? '#64748b' : '#94a3b8'} 
        />
      </View>
    </Pressable>
  );
}

export default function ExportScreen() {
  const { darkMode } = useTheme();
  const { userData } = useUser();
  const dashboardStatus = useDashboardStatus();
  const router = useRouter();
  const [isExporting, setIsExporting] = useState(false);

  const generateHealthReport = () => {
    const today = new Date().toLocaleDateString();
    
    let report = `Health Report - ${today}\n`;
    report += `Generated by Migraine Tracker\n\n`;
    
    // User info
    report += `User: ${userData?.name || 'Anonymous'}\n`;
    report += `Age Group: ${userData?.ageBracket || 'Not specified'}\n\n`;
    
    // Dashboard metrics
    report += `--- Daily Health Metrics ---\n`;
    if (dashboardStatus.meals) {
      report += `Meals: ${dashboardStatus.meals.unit} (${dashboardStatus.meals.status})\n`;
    }
    if (dashboardStatus.hydration) {
      report += `Hydration: ${dashboardStatus.hydration.unit} (${dashboardStatus.hydration.status})\n`;
    }
    if (dashboardStatus.alcohol) {
      report += `Alcohol: ${dashboardStatus.alcohol.unit} (${dashboardStatus.alcohol.status})\n`;
    }
    
    // Device metrics
    if (dashboardStatus.deviceMetrics.length > 0) {
      report += `\n--- Device Metrics ---\n`;
      dashboardStatus.deviceMetrics.forEach(metric => {
        report += `${metric.label}: ${metric.unit} (${metric.status})\n`;
      });
    }
    
    // External metrics
    if (dashboardStatus.externalMetrics.length > 0) {
      report += `\n--- External Metrics ---\n`;
      dashboardStatus.externalMetrics.forEach(metric => {
        report += `${metric.label}: ${metric.unit} (${metric.status})\n`;
      });
    }
    
    report += `\nOverall Status: ${dashboardStatus.overallStatus}\n`;
    report += `Last Updated: ${dashboardStatus.lastUpdated || 'No data'}\n`;
    
    return report;
  };

  const exportHealthData = async () => {
    // Navigate to the health metrics visualization page instead of exporting text
    // This will show graphs that can be shared with healthcare professionals
    router.push('/health-metrics' as any);
  };

  const exportMigraineLog = async () => {
    // Navigate to the migraine tracking visualization page
    // This will show line graphs and AI analysis
    router.push('/migraine-tracking' as any);
  };

  const exportFullReport = async () => {
    // Navigate to the complete report page that combines everything
    // This will show comprehensive health and migraine analysis
    router.push('/complete-report' as any);
  };

  return (
    <View style={[styles.container, darkMode && styles.containerDark]}>
      <NavigationBar
        title="Export Data"
        subtitle="Share your health data and insights"
        showBackButton={true}
      />
      
      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        <View style={styles.section}>
          <Text style={[styles.sectionTitle, darkMode && styles.sectionTitleDark]}>
            Export Options
          </Text>
          <Text style={[styles.sectionDescription, darkMode && styles.sectionDescriptionDark]}>
            Choose what data you'd like to export and share
          </Text>
        </View>

        <View style={styles.optionsContainer}>
          <ExportOption
            iconName="bar-chart"
            title="Health Metrics"
            description="View 30-day health trends with professional charts"
            onPress={exportHealthData}
            darkMode={darkMode}
            color="#10b981"
            bgColor="#d1fae5"
          />
          
          <ExportOption
            iconName="pulse"
            title="Migraine Log"
            description="View 30-day migraine patterns with AI insights"
            onPress={exportMigraineLog}
            darkMode={darkMode}
            color="#9333ea"
            bgColor="#f3e8ff"
          />
          
          <ExportOption
            iconName="document-text"
            title="Complete Report"
            description="Comprehensive health & migraine analysis with AI insights"
            onPress={exportFullReport}
            darkMode={darkMode}
            color="#2563eb"
            bgColor="#dbeafe"
          />
        </View>

        <View style={[styles.infoContainer, darkMode && styles.infoContainerDark]}>
          <View style={styles.infoHeader}>
            <Ionicons 
              name="information-circle" 
              size={20} 
              color={darkMode ? '#60a5fa' : '#3b82f6'} 
              style={styles.infoIcon}
            />
            <Text style={[styles.infoTitle, darkMode && styles.infoTitleDark]}>
              Privacy Notice
            </Text>
          </View>
          <Text style={[styles.infoText, darkMode && styles.infoTextDark]}>
            Your health data is exported directly from your device and shared through your chosen method. 
            We never store or access your exported data on our servers.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  containerDark: {
    backgroundColor: '#0f172a',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 100, // Space for floating menu
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: 8,
  },
  sectionTitleDark: {
    color: '#f1f5f9',
  },
  sectionDescription: {
    fontSize: 16,
    color: '#64748b',
    lineHeight: 24,
  },
  sectionDescriptionDark: {
    color: '#94a3b8',
  },
  optionsContainer: {
    gap: 16,
    marginBottom: 32,
  },
  exportOption: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  exportOptionDark: {
    backgroundColor: '#1e293b',
    borderColor: '#334155',
  },
  exportOptionPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.8,
  },
  iconContainer: {
    width: 56,
    height: 56,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  textContainer: {
    flex: 1,
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: 4,
  },
  titleDark: {
    color: '#f1f5f9',
  },
  description: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 20,
  },
  descriptionDark: {
    color: '#94a3b8',
  },
  arrowContainer: {
    marginLeft: 12,
  },
  infoContainer: {
    backgroundColor: '#eff6ff',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
  infoContainerDark: {
    backgroundColor: '#1e3a8a',
    borderColor: '#1e40af',
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoIcon: {
    marginRight: 8,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e40af',
  },
  infoTitleDark: {
    color: '#93c5fd',
  },
  infoText: {
    fontSize: 14,
    color: '#1e40af',
    lineHeight: 20,
  },
  infoTextDark: {
    color: '#bfdbfe',
  },
});
